env:
  commonjs: true
  es6: true
  node: true
  jest: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  func-names: ["error", "as-needed"]
  # space-before-function-paren: ["error", {"anonymous": "never", "never": "always", "asyncArrow": "always"}]
  max-len: ["error", 120]
  no-underscore-dangle: ["error", { "allow": ["_id", "_str"]}]
  no-plusplus: ["error", {"allowForLoopAfterthoughts": true}]
  import/no-unresolved: [2, { ignore: ["^meteor/"] }]
  comma-dangle: ["error", "only-multiline"]
